### ISSUE TITLE
the audio preblem

### ISSUE THREAD

**Issue by findyy99** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#31]
Hi, I've tried .the newest release, the audio icon is gray at the beginning of the boot, And after a while, It will be normal.And, unfortunately, the plug problem is still there. English poor, Sorry! But, still thanks!

**Comment by surrogatecode** [comment]
(I am on a X1C so some things may behave differently from the T450)

Same here, the audio takes a while to come on after booting the system. 
However, it is working well after this brief delay.

The audio will also fail after a forced hibernation (running out of battery).
I have no idea how to fix this, but it is a very unlikely scenario (hibernation).

The hissing was persistent even after the latest patch. ALC-pugin-fix is working, however only with manual activation. Installing it had seemingly no effect until it did just somehow magically fix itself (I suspect removing kexts from S/E/ and running them only via clover's other/ folder had an effect.)

**Comment by jsassu20** [comment]
are you usl=ing layout id 55? Try adding the bootarguement alcid=55

**Comment by surrogatecode** [comment]
I did not use the additional boot-argument, yet. Thanks.

I have added alcid=55, reboot, hissing.
I have removed the ALCPlugin, added alcid=55, reboot, hissing.

I have tried just using alcid=layout-id to see if the boot-argument has any effect, which resulted in the audio driver not coming on, at all. 

It remains, that there is a hiss over the headphones most times, even with the ALCPuginFix installed. There is random moments, where the ALCPluginFix will work, but I do not know the cause of this, yet.

**Comment by jianzhao0806** [comment]
> I did not use the additional boot-argument, yet. Thanks.
> 
> 我还没有使用附加的 boot-argument，谢谢。
> 
> I have added alcid=55, reboot, hissing.
> I have removed the ALCPlugin, added alcid=55, reboot, hissing.
> 
> 我已经移除了 ALCPlugin，增加了 alcid 55，重启，嘶嘶声。
> 
> I have tried just using alcid=layout-id to see if the boot-argument has any effect, which resulted in the audio driver not coming on, at all.
> 
> 我只是尝试使用 alcid layout-id 来查看 boot-argument 是否有任何效果，这导致音频驱动程序根本无法启动。
> 
> It remains, that there is a hiss over the headphones most times, even with the ALCPuginFix installed. There is random moments, where the ALCPluginFix will work, but I do not know the cause of this, yet.
> 
> 即使安装了 ALCPuginFix，大多数时候耳机上仍然会有嘶嘶声。 也有一些偶然的时刻，在这些时刻 ALCPluginFix 会工作，但是我还不知道原因。
> 
> I may be missing settings in the Clover Configurator. Looking into it, now.
> 
> 我可能会失去三叶草配置器的设置。正在调查。

maybe you can like me, when you boot up, you can sleep manually, and you will find the hissing gone

**Comment by surrogatecode** [comment]
Yes, that may be why the hissing disappears sometimes. Still working on it.

**Comment by jianzhao0806** [comment]
> Yes, that may be why the hissing disappears sometimes. Still working on it.

have you tried the opencore repo?

**Comment by surrogatecode** [comment]
@jsassu20 I think, because I was using your initial config.plist as a starting point, the layout-id was set to 55 via Devices->Properties->PciRoot(0x0)/Pci(0x1b,0x0) already.

I have read more about AppleALC.
The X1C3 (and T450?) is using the ALC292 codec (possible layout-id's 12, 18, 28, 32, 55). 
I have tried using layout-id 32, as it is specified as the layout for the T450s in the ALC292 [info.plist](https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC292/Info.plist).

result: layout-id 32, the audio-icon comes on immediately, i.e. driver seems to be loaded without delay. I have re-installed the ALCPluginFix and rebooted, headphones have worked without a hiss.

@jianzhao0806 No, I am not interested, yet. OpenCore is still experimental/work in progress and I want a stable system. I think I have fixed it, see above, try using "layout-id 32". 

You need to change it via Clover Configurator or another plist-editor. Open you config.plist -> Devices -> Properties->PciRoot(0x0)/Pci(0x1b,0x0) -> layout-id, enter 32. Add the boot-argument alcid=32 just in case, but I do not think the boot-argument is needed.

**Comment by Nolivera007** [comment]
@surrogatecode send me your EFI folder, please I have a audio problem on thinkpad t450 Catalina.

**Comment by surrogatecode** [comment]
@Nolivera007 Hi Noe, I am not sure if the EFI folder will be of any help to you, as I am not running Catalina nor a T450. See above:
> (I am on a X1C so some things may behave differently from the T450)

Keep in mind, the sound issues I encountered were less related to the general makeup of the EFI folder, and do not need a copy of the EFI folder per se. I essentially did three things. Also, the 3rd step is more of a hack. It works for me, with my configuration, on my laptop. It may have a very different outcome on your T450.

1. Make sure the ALC-Plugin-Fix properly starts after boot.
2. Edit the config.plist to have a working layout-id (easily done with Clover Configurator).
3. Remove all clover-related kexts from the EFI/CLOVER/kexts/System & S/L/E/

The EFI folder does **not** contain a config.plist, so please copy your config.plist into the EFI folder before rebooting!! You need to use your own config.plist to not lose your very own SMBIOS settings. -> [https://we.tl/t-cOSZ2Vi9kz](https://we.tl/t-cOSZ2Vi9kz)
